---
title: "St. Louis Lead Inequality"
author: "Carmen"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
execute:
  echo: false
  warning: false
  output: false
---

```{r}
library(tidyverse)
library(janitor)
```

```{r}
stl_lead <- read_csv(here::here("data", "stl_blood_lead.csv"),)

stl_lead <- stl_lead |> clean_names()

summary(stl_lead)
dim(stl_lead)
names(stl_lead)
```

```{r}
stl_lead_prop <- stl_lead

stl_lead_prop$prop_white <- (stl_lead_prop$white/stl_lead_prop$total_pop)*100
```

```{r}
#| output: true
#| fig-cap: "Figure 1"
#| fig-alt: "Scatterplot"
stl_lead_plot <- ggplot(data = stl_lead_prop,
       aes(x = prop_white,
           y = pct_elevated))+
  geom_point(aes(size = 2, color = pct_elevated), show.legend = FALSE)+
  scale_color_gradient(low = "blue", high = "red")+
  theme_minimal()+
  labs(x = "Percent White",
       y = "Percent Elevated",
       title = "Elevated Blood Lead Levels Across St. Louis Census Tracts")

stl_lead_plot

ggsave(here::here("figs", "stl_lead_plot.png"), height = 6, width = 5)
```

Overall, census tracts with lower percentages of white residents reported higher blood lead levels. 

```{r}
#| output: true
#| fig-cap: "Figure 2"
#| fig-alt: "Histogram"
ggplot(data = stl_lead_prop, aes(x = pct_elevated))+
  geom_histogram(color = "blue", fill = "orange", size = 2)+
  theme_minimal()+
  labs(x = "Percent Elevated",
       y = "Frequency",
       title = "Frequency of Percent Elevated Blood Lead Levels")

ggsave(here::here("figs", "pct_elevated_hist.png"), height = 6, width = 5)
```






